import type { SchoolData } from "@/domain/types";
export type Collection = Exclude<keyof SchoolData, "settings" | "version">;
export type Row = Record<string, unknown>;
export const names: Record<string, string> = {
  schoolYears: "Anos escolares",
  classes: "Turmas",
  subjects: "Disciplinas",
  classSubjects: "Disciplinas por turma",
  schedules: "Aulas",
  eventTypes: "Tipos de evento",
  events: "Eventos",
  resources: "Materiais",
  subjectResources: "Materiais por disciplina",
  activities: "Atividades",
  recipes: "Receitas de estudo",
  rules: "Pesos do algoritmo",
  phases: "Fases de preparação",
  reasonTemplates: "Explicações do plano",
};
export const fieldNames: Record<string, string> = {
  id: "Identificador",
  name: "Nome",
  code: "Sigla / código",
  active: "Ativo",
  order: "Ordem",
  schoolYearId: "Ano escolar",
  classId: "Turma",
  subjectId: "Disciplina",
  resourceId: "Material",
  eventTypeId: "Tipo de evento",
  color: "Cor",
  icon: "Ícone",
  weekday: "Dia da semana (0 = domingo)",
  periodNumber: "Número da aula",
  startTime: "Horário inicial",
  endTime: "Horário final",
  startDate: "Data inicial",
  endDate: "Data final",
  title: "Título",
  description: "Descrição",
  importance: "Importância (0–5)",
  affectsStudyPlan: "Influencia o plano",
  metadata: "Metadados (JSON)",
  studyWeight: "Peso no planejamento",
  preparationDays: "Dias de preparação",
  blocksStudy: "Bloqueia estudo na data",
  url: "Endereço do material",
  weeklyMinimum: "Mínimo semanal",
  preferredWeekdays: "Dias preferidos (JSON, 0 = domingo)",
  mandatoryBonus: "Bônus para cumprir o mínimo",
  priority: "Ordem de preferência",
  instruction: "Instrução para o aluno",
  durationMinutes: "Duração em minutos",
  activityType: "Tipo de atividade",
  difficulty: "Dificuldade",
  steps: "Etapas (JSON: id, activityId, durationMinutes, order)",
  value: "Valor",
  daysBeforeMin: "Mínimo de dias antes",
  daysBeforeMax: "Máximo de dias antes",
  recommendedActivityType: "Tipo de atividade recomendado",
  text: "Texto da explicação",
  schoolName: "Nome da escola",
  academicYear: "Ano letivo",
  planDefaultWeeks: "Semanas por plano",
  minimumStudyMinutes: "Duração mínima de sessão",
  maxStudyMinutesPerDay: "Limite diário em minutos",
  targetStudyLoadPercentage: "Fração do tempo disponível (0,1 a 1)",
  availabilitySlotMinutes: "Duração das células de horário",
  weekdays: "Dias disponíveis (JSON, 0 = domingo)",
  allowHolidays: "Permitir estudo em feriados",
};
export const references: Record<string, Collection> = {
  schoolYearId: "schoolYears",
  classId: "classes",
  subjectId: "subjects",
  resourceId: "resources",
  eventTypeId: "eventTypes",
};
export function defaultRow(key: Collection, data: SchoolData): Row {
  const id = crypto.randomUUID(),
    subjectId = data.subjects[0]?.id ?? "",
    classId = data.classes[0]?.id ?? "",
    resourceId = data.resources[0]?.id ?? "";
  const map: Record<Collection, Row> = {
    schoolYears: {
      id,
      name: "Novo ano",
      order: data.schoolYears.length,
      active: true,
    },
    classes: {
      id,
      name: "Nova turma",
      code: "NOVA",
      schoolYearId: data.schoolYears[0]?.id ?? "",
      order: 0,
      active: true,
    },
    subjects: {
      id,
      name: "Nova disciplina",
      code: "NOV",
      icon: "BookOpen",
      color: "#7755CC",
      active: true,
    },
    classSubjects: { id, classId, subjectId },
    schedules: {
      id,
      classId,
      subjectId,
      weekday: 1,
      periodNumber: 6,
      startTime: "12:00",
      endTime: "12:50",
    },
    eventTypes: {
      id,
      name: "Novo tipo",
      code: "novo_tipo",
      studyWeight: 20,
      preparationDays: 7,
      color: "#7755CC",
      icon: "CalendarDays",
      blocksStudy: false,
    },
    events: {
      id,
      title: "Novo evento",
      description: "",
      eventTypeId: data.eventTypes[0]?.id ?? "",
      startDate: new Date().toISOString().slice(0, 10),
      endDate: new Date().toISOString().slice(0, 10),
      schoolYearId: null,
      classId: null,
      subjectId: null,
      importance: 3,
      affectsStudyPlan: true,
      metadata: {},
    },
    resources: {
      id,
      name: "Novo material",
      description: "",
      url: "",
      active: true,
      weeklyMinimum: 0,
      preferredWeekdays: [],
      mandatoryBonus: 25,
    },
    subjectResources: { id, subjectId, resourceId, priority: 1 },
    activities: {
      id,
      subjectId: null,
      resourceId: null,
      name: "Nova atividade",
      instruction: "Revise os registros da aula e anote suas dúvidas.",
      durationMinutes: 30,
      activityType: "practice",
      difficulty: 1,
      priority: 1,
      active: true,
    },
    recipes: {
      id,
      name: "Nova receita",
      subjectId: null,
      resourceId: null,
      durationMinutes: 30,
      activityType: "practice",
      active: true,
      steps: [
        {
          id: crypto.randomUUID(),
          activityId: data.activities[0]?.id ?? "",
          durationMinutes: 30,
          order: 0,
        },
      ],
    },
    rules: {
      id,
      code: "nova_regra",
      name: "Nova regra",
      description: "",
      value: 0,
      active: true,
    },
    phases: {
      id,
      eventTypeId: data.eventTypes[0]?.id ?? "",
      daysBeforeMin: 1,
      daysBeforeMax: 7,
      weight: 20,
      recommendedActivityType: "practice",
    },
    reasonTemplates: { id, code: "NOVO_MOTIVO", text: "Descrição do motivo." },
  };
  return map[key];
}
